# Generated by Django 3.1.2 on 2020-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=0, verbose_name='売買ID'),
        ),
    ]
